### ISSUE TITLE
Agent panics when resource is nil

### ISSUE THREAD

**Issue by matheus-moraes-caylent** [codefresh-io/argocd-agent#147]
Hi,

I'm trying to use the argocd-agent for CodeFresh but the agent panics after running for a few seconds. Here it's the stack trace:

```
I0505 13:27:42.836187       1 logger.go:31] Queue size 4
I0505 13:27:43.021653       1 logger.go:31] Send application resources for app argo-int-green with history -1
E0505 13:27:43.153341       1 logger.go:35] can`t find history id for application argo-mint-lioness-green, because history list is empty
E0505 13:27:43.278435       1 logger.go:35] Failed to retrieve manifest repo git information , reason: GET https://api.github.com/repos///commits/0.9.8: 404 Not Found []
I0505 13:27:43.424745       1 logger.go:31] Detect new gitops application argo-mint-lioness-green, initiate initialization
I0505 13:27:43.424819       1 logger.go:31] Successfully sent environment "argo-mint-lioness-green" update to codefresh, services count 2
I0505 13:27:43.671909       1 logger.go:31] Send application resources for app argo-mint-lioness-green with history -1
E0505 13:27:43.796981       1 logger.go:35] Failed to handle new gitops application argo-native-vulture-green, reason: Failed to retrieve application, reason 404 Not Found
E0505 13:27:43.814612       1 logger.go:35] can`t find history id for application argo-pre-prd-green, because history list is empty
E0505 13:27:43.950666       1 logger.go:35] Failed to retrieve manifest repo git information , reason: GET https://api.github.com/repos///commits/0.9.8: 404 Not Found []
I0505 13:27:44.090830       1 logger.go:31] Detect new gitops application argo-pre-prd-green, initiate initialization
I0505 13:27:44.090851       1 logger.go:31] Successfully sent environment "argo-pre-prd-green" update to codefresh, services count 2
I0505 13:27:44.422194       1 logger.go:31] Send application resources for app argo-pre-prd-green with history -1
E0505 13:27:44.544484       1 logger.go:35] Failed to handle new gitops application argo-rollouts-ample-hedgehog-green, reason: Failed to retrieve application, reason 404 Not Found
E0505 13:27:44.559602       1 logger.go:35] can`t find history id for application argo-rollouts-daring-catfish, because history list is empty
I0505 13:27:44.662118       1 logger.go:31] Retrieve commit message "[SKIP CI] create demo environment demo-cindy matthew" for repo "git@github.com:my-company/myrepo.git" 
I0505 13:27:44.665054       1 logger.go:31] Successfully sent environment "demo-cindy" update to codefresh, services count 0
E0505 13:27:44.678889       1 logger.go:35] Failed to retrieve manifest repo git information , reason: GET https://api.github.com/repos///commits/0.3.10: 404 Not Found []
I0505 13:27:44.837497       1 logger.go:31] Detect new gitops application argo-rollouts-daring-catfish, initiate initialization
I0505 13:27:44.837519       1 logger.go:31] Successfully sent environment "argo-rollouts-daring-catfish" update to codefresh, services count 0
E0505 13:27:44.952207       1 logger.go:35] Failed to update environment, reason: Failed to retrieve application, reason 404 Not Found
I0505 13:27:44.952227       1 logger.go:31] Queue size 3

panic: interface conversion: interface {} is nil, not []interface {}



goroutine 6284 [running]:
github.com/codefresh-io/argocd-listener/agent/pkg/events.(*RolloutHandler).Handle(0xc0002c12c0, 0x11cb1a0, 0xc003df8c80, 0x39, 0xc001005de8)
	/go/src/github.com/codefresh-io/argocd-listener/agent/pkg/events/rollout.go:87 +0xa05
github.com/codefresh-io/argocd-listener/agent/pkg/scheduler.(*envInitializerScheduler).handleNewApplications(0xc000348460, 0xc003e3f800, 0x64, 0x80)
	/go/src/github.com/codefresh-io/argocd-listener/agent/pkg/scheduler/env_initializer.go:87 +0x25e
github.com/codefresh-io/argocd-listener/agent/pkg/scheduler.(*envInitializerScheduler).handleEnvDifference(0xc000348460)
	/go/src/github.com/codefresh-io/argocd-listener/agent/pkg/scheduler/env_initializer.go:116 +0x14e
github.com/robfig/cron/v3.FuncJob.Run(0xc000108110)
	/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:136 +0x25
github.com/robfig/cron/v3.(*Cron).startJob.func1(0xc00012c0a0, 0x1594dc0, 0xc000108110)
	/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312 +0x61
created by github.com/robfig/cron/v3.(*Cron).startJob
	/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:310 +0x73
```

It always fails when a resource is returned empty. It looks like a good idea to check if the resource it's not nil before converting it.

Appreciate any feedback you can give

**Comment by pasha-codefresh** [comment]
hi @matheus-moraes-caylent . Thank you for report.

**Comment by pasha-codefresh** [comment]
@matheus-moraes-caylent let me know if it still happens. Fix is pushed

**Comment by matheus-moraes-caylent** [comment]
Thanks @pasha-codefresh, there is an updated docker image that I can test?

**Comment by pasha-codefresh** [comment]
@matheus-moraes-caylent just restart a pod with argocd agent, it will pull latest image

**Comment by matheus-moraes-caylent** [comment]
@pasha-codefresh it worked, thanks! I'm closing this issue and my PR
